### ISSUE TITLE
Site health says oidc keys are invalid, but they aren't

### ISSUE THREAD

**Issue by psrpinto** [Automattic/wp-openid-connect-server#103]
The plugin is functional, but the site health says the keys are invalid:

<img width="842" alt="Screenshot 2023-10-10 at 16 19 28" src="https://github.com/Automattic/wp-openid-connect-server/assets/550401/f18e5b3f-0f76-482c-884f-2e3799c36cda">

This happens with keys produced as per instructions in the readme:

```shell
openssl genrsa -out oidc.key 4096
openssl rsa -in oidc.key -pubout -out public.key
```

**Comment by jeherve** [comment]
I ran into this issue as well. Could you try to update the format of the key you pasted in your site's `wp-config.php` to use `-----BEGIN PUBLIC KEY-----` and `-----END PUBLIC KEY-----` as the markers for the beginning and end of the key. 

Hopefully that will help!
