### ISSUE TITLE
Sticky Consent - Skip page that asks user to grant permission if it has already been granted

### ISSUE THREAD

**Issue by psrpinto** [Automattic/wp-openid-connect-server#11]
If the user has already previously granted permission, the page that asks for permission (as per screenshot below) could be skipped. This would remove one step from subsequent authentication flows (after the initial one). I believe this how most OIDC implementations I've encountered work (e.g. Google).

<img width="570" alt="Screenshot 2022-08-11 at 14 59 38" src="https://user-images.githubusercontent.com/550401/184150931-6ed6070e-8092-46d7-8029-831c3afc9b1f.png">

**Comment by akirk** [comment]
This could be stored as a user meta.

**Comment by ashfame** [comment]
Documenting approach: Save timestamp of consent in usermeta and upon 30 days (this can be made configurable as well) we can prompt the user for consent again. Later on, we can worry about fine grain control around it.
