### ISSUE TITLE
Make the Consent Screen go through wp-login

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-openid-connect-server#38]
As @dd32 mentioned: Use wp-login.php as the templating basis, rather than the sites theme, ie. wp-login.php?action=openid-authenticate with the [`login_form_{$action}`](https://developer.wordpress.org/reference/hooks/login_form_action/) filter. That’ll result in a more native experience for other users of the plugin, as it’ll respect the WordPress authentication styling and any other customizations a site has (ie. on WordPress.org it would force it to redirect via login.wordpress.org, and on other sites, it would force it to respect their custom login branding).

**Comment by ashfame** [comment]
Have a draft PR going for this https://github.com/Automattic/wp-openid-connect-server/pull/43

Quoting its description here:

> We simply don't register authenticate endpoint and attach the template for that to wp-login.php action hook but this isn't a clean implementation either. So, leveraging existing styles and look isn't an advantage at all. This will easily break in styling in the wild.
> Also, had to hide the login form that still gets rendered despite a custom action by using css.
> But I understand the reasons for supporting diverted login pages, which seems to be the only merit to move in this direction from our existing approach.

But since, I don't know how WP.org login works, I am not sure what's needed to make it compatible with that.
