### ISSUE TITLE
Make clients list filterable

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-openid-connect-server#39]
Re-evaluate why the client list is done through a function call `oidc_clients()`. Couldn't it just be done as a filter? I think to recall that I chose that implementation so that the clients could be defined in wp-config. If we go the filter route, they need to be added as an mu-plugin or through UI.

**Comment by ashfame** [comment]
Currently `oidc_clients()` is invoked at `wp_loaded` hook, so I don't see any reason why it won't work if defined normally in code.

I would propose building an options page in wp-admin, where we can configure clients and have the option of generating RSA keys (if user doesn't wish to provide) which would cover https://github.com/Automattic/wp-openid-connect-server/issues/40 as well. Thoughts? cc: @psrpinto

**Comment by akirk** [comment]
Yes but it's not a priority now because we'll define them programmatically on .org for now. Let's just add an `apply_filters` for now and address the other issues.

**Comment by ashfame** [comment]
Sure thing!

**Comment by psrpinto** [comment]
Defining it through `apply_filters` makes sense to me 👍
