### ISSUE TITLE
Current JWKS endpoint doesn't work in a subdirectory WP install

### ISSUE THREAD

**Issue by ashfame** [Automattic/wp-openid-connect-server#4]
I think, it's better to have JWKS endpoint as a REST route itself. But since it was a REST route originally wondering what was the reason behind the move?

**Comment by akirk** [comment]
I moved it because it has a `.well-known` URL.

**Comment by ashfame** [comment]
**Documenting conversation:** Its not strictly a `.well-known` url if we have WP in a sub-directory install because the url becomes `https://domain.org/dir/.well-known/jwks.json`.

Nor its expected out of hosts to make keys available at this specific url. Perhaps just a convention. Discovery endpoint is expected here `https://server.com/.well-known/openid-configuration`.

Even if it was in specification, we wouldn't be able to do it for sub-directory WP installs. But for root WP installs, this works, so we are keeping it. Non-root WP installs would have to specify a custom endpoint anyway.

https://github.com/Automattic/wp-openid-connect-server/issues/6 has been created to make it work with sub-directory WP installs.
