### ISSUE TITLE
Consent screen would likely mess with caching

### ISSUE THREAD

**Issue by ashfame** [Automattic/wp-openid-connect-server#5]
Suggest we move it to as an action handler under `admin-ajax.php` considering it's very likely to have that excluded from caching as part of general WP setup?

**Comment by akirk** [comment]
Could you explain in more detail how you would do that? It's not an AJAX call and we cannot assume that all users have access to wp-admin.

**Comment by ashfame** [comment]
In WP installs, URL we have for authorization **might** get cached by a caching plugin and without the exclusion it might cause issues. http calls to `admin-ajax.php` are never cached by any of the caching plugins and any custom caching solutions are expected to exclude that url anyway, for a functional WP so if we render the consent screen on admin-ajax.php url like `/wp-admin/admin-ajax.php?action=oidc_consent_screen` we might be better off?

> It's not an AJAX call and we cannot assume that all users have access to wp-admin.

Yep, its not an ajax call, so we would be breaking some semantics here. However, I am not sure what you mean by "we cannot assume that all users have access to wp-admin". `admin-ajax.php` would work for every user.

**Comment by psrpinto** [comment]
My assumption for these kind of plugins would be that they would respect caching-related HTTP headers, so setting said headers could fix the issue.

Could you provide some examples of caching plugins @ashfame? So we can check if they do indeed respect these headers.

**Comment by akirk** [comment]
I am not 100% sure but don't caching plugins only kick into effect for anonymous users? As soon as you are logged in, the page shouldn't come from cache anyway.

**Comment by ashfame** [comment]
Yeah! You are right, the consent/authorization form isn't served until the user logs in, so this is indeed not an issue. Closing it.
