### ISSUE TITLE
Should we rename this repo to match the plugin directory slug?

### ISSUE THREAD

**Issue by psrpinto** [Automattic/wp-openid-connect-server#65]
Slug is `openid-connect-server` (https://wordpress.org/plugins/openid-connect-server) so could make sense to rename this repo to that as well.

**Comment by ashfame** [comment]
I think `wp-` prefix make sense since this is a WordPress plugin? That probably is a WP thing more than general convention.

**Comment by psrpinto** [comment]
Ok, was just checking, closing the issue.
