### ISSUE TITLE
Rename the plugin loader file and also the repo

### ISSUE THREAD

**Issue by akirk** [Automattic/wp-openid-connect-server#66]
We have submitted the plugin to the plugin directory under the name `openid-connect-server` https://wordpress.org/plugins/openid-connect-server/

The file that actually loads the plugin is still called `wp-openid-connect-server.php` which means that we have an inconsistency in path and filename: `openid-connect-server/wp-openid-connect-server.php`

It works because WordPress checks all PHP files inside the directory for a comment containing `Plugin Name:` but I think for consistency we should rename it.

**Comment by ashfame** [comment]
I created a PR to change the main plugin file.

For repo, I think it makes sense to include `wp-` prefix for a quick indication that its a WP plugin?

**Comment by akirk** [comment]
Agreed, let's keep the repo name.
