### ISSUE TITLE
PHP Warning during pentesting rest api endpoints

### ISSUE THREAD

**Issue by dd32** [Automattic/wp-openid-connect-server#74]
The various rest api endpoints should have their accepted arguements validated by the REST API server prior to passing it to the application.

This would mean passing the `args` parameter of register_rest_route() or the `schema` param.

As the plugin uses a custom routing layer, and passes most of the handling of the endpoint off to a third-party library, it's a bit hard to properly sanitize the request.. 

```
PHP Warning: Illegal offset type in isset or empty
Source: GET https://example.org/wp-json/openid-connect/authorize?client_id[%24testing]=1&redirect_uri=http://localhost:9000/callback&response_type=code&scope=openid%20email&state=stategoeshere
Timestamp: Mon, 03 Apr 2023 04:50:54 +0000 (1680497454)
File: wp-content/plugins/openid-connect-server/src/Storage/ClientCredentialsStorage.php
```

**Comment by ashfame** [comment]
Thanks @dd32!

I have added expected args specs for other endpoints as well in your PR, if you want to test it again & see if its all good now?

**Comment by dd32** [comment]
I can't really test this past what you can, and you're better placed to do so.

These were just the warnings generated in production from people brute-force testing it looking for vulnerabilities.

**Comment by ashfame** [comment]
Gotcha! I thought maybe you were in a position to test them to see if all warnings are fixed. All good 👍
