### ISSUE TITLE
Adding custom user claims (eg roles)

### ISSUE THREAD

**Issue by david02871** [Automattic/wp-openid-connect-server#80]
Could we add a `oidc_custom_user_claims` filter hook to the `UserClaimsStorage` class for custom claims?

In our use case we need to add the WordPress user's roles for use by the client application.

https://github.com/Automattic/wp-openid-connect-server/blob/b55d7ed8cc2ba34945e72f539382f6abb3af4c32/src/Storage/UserClaimsStorage.php#L33-L48

Open to suggestions if there is another way of doing this that I have missed.

**Comment by psrpinto** [comment]
@david02871 @braders Release 1.2.1 of the plugin now has `oidc_user_claims` filter hook. Thanks for bringing this issue to our attention.
